# Generated by Django 4.2.16 on 2024-12-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=100)),
                ('rankMin', models.FloatField()),
                ('rankMax', models.FloatField()),
                ('rankPrio', models.TextField()),
                ('safetyMin', models.FloatField()),
                ('safetyMax', models.FloatField()),
                ('safetyPrio', models.TextField()),
                ('accMin', models.FloatField()),
                ('accMax', models.FloatField()),
                ('accPrio', models.TextField()),
                ('ISRMin', models.FloatField()),
                ('ISRMax', models.FloatField()),
                ('ISRPrio', models.TextField()),
                ('CoLMin', models.FloatField()),
                ('CoLMax', models.FloatField()),
                ('CoLPrio', models.TextField()),
                ('rentMin', models.FloatField()),
                ('rentMax', models.FloatField()),
                ('rentPrio', models.TextField()),
                ('groceryMin', models.FloatField()),
                ('groceryMax', models.FloatField()),
                ('groceryPrio', models.TextField()),
                ('transportMin', models.FloatField()),
                ('transportMax', models.FloatField()),
                ('transportPrio', models.TextField()),
                ('recreationMin', models.FloatField()),
                ('recreationMax', models.FloatField()),
                ('recreationPrio', models.TextField()),
                ('healthcareBudgetMin', models.FloatField()),
                ('healthcareBudgetMax', models.FloatField()),
                ('healthcareBudgetPrio', models.TextField()),
                ('tuitionBudgetMin', models.FloatField()),
                ('tuitionBudgetMax', models.FloatField()),
                ('tuitionBudgetPrio', models.TextField()),
                ('major', models.TextField()),
            ],
        ),
    ]
