# Generated by Django 4.2.16 on 2024-12-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='savedUniversities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('rank', models.IntegerField()),
                ('acc', models.FloatField()),
                ('estimatedCost', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='forma',
            name='continent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
