# Generated by Django 4.2.16 on 2024-12-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_saveduniversities_alter_forma_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma',
            name='safetyMax',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='forma',
            name='safetyMin',
            field=models.TextField(),
        ),
    ]
