# Generated by Django 4.2.18 on 2025-01-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_saveduniversities_choiceno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('rank', models.IntegerField()),
                ('tuition', models.FloatField()),
                ('internationalStudentRatio', models.FloatField()),
                ('acceptanceRate', models.FloatField()),
                ('safetyIndex', models.FloatField()),
                ('costOfLiving', models.FloatField()),
                ('rentCost', models.FloatField()),
                ('groceryCost', models.FloatField()),
                ('transportCost', models.FloatField()),
                ('recreationCost', models.FloatField()),
                ('healthcareCost', models.FloatField()),
                ('estimatedCost', models.FloatField()),
                ('website', models.CharField(max_length=200)),
                ('computerScience', models.BooleanField()),
                ('business', models.BooleanField()),
                ('economics', models.BooleanField()),
                ('psychology', models.BooleanField()),
                ('biology', models.BooleanField()),
                ('law', models.BooleanField()),
                ('medicine', models.BooleanField()),
                ('mathematics', models.BooleanField()),
                ('art', models.BooleanField()),
                ('physics', models.BooleanField()),
            ],
        ),
    ]
