# Generated by Django 4.2.18 on 2025-01-30 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_saveduniversities_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('rank', models.IntegerField()),
                ('acc', models.FloatField()),
                ('estimatedCost', models.FloatField()),
                ('major', models.CharField(max_length=100, null=True)),
                ('website', models.CharField(max_length=200, null=True)),
                ('choiceNo', models.IntegerField(default=0)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('inputInformation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.forma')),
                ('results', models.ManyToManyField(to='api.uni')),
            ],
        ),
    ]
