# Generated by Django 4.2.18 on 2025-01-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_uni_searchhistoryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistoryitem',
            name='inputInformation',
        ),
        migrations.RemoveField(
            model_name='searchhistoryitem',
            name='results',
        ),
        migrations.DeleteModel(
            name='Forma',
        ),
        migrations.AddField(
            model_name='searchhistoryitem',
            name='inputInformation',
            field=models.ManyToManyField(to='api.uni'),
        ),
        migrations.AddField(
            model_name='searchhistoryitem',
            name='results',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
