# Generated by Django 4.2.18 on 2025-01-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_searchhistoryitem_inputinformation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistoryitem',
            name='inputInformation',
        ),
        migrations.RemoveField(
            model_name='searchhistoryitem',
            name='results',
        ),
        migrations.AddField(
            model_name='searchhistoryitem',
            name='inputInformation',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchhistoryitem',
            name='results',
            field=models.ManyToManyField(to='api.uni'),
        ),
    ]
