# Generated by Django 4.2.18 on 2025-01-31 00:12

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_searchhistoryitem_inputinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistoryitem',
            name='inputInformation',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
