# Generated by Django 4.2.18 on 2025-01-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_saveduniversities_choiceno_saveduniversities_major_and_more'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='universities_saved',
            field=models.ManyToManyField(related_name='users', to='api.saveduniversities'),
        ),
    ]
