# Generated by Django 4.2.18 on 2025-01-15 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_forma_safetymax_alter_forma_safetymin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveduniversities',
            name='city',
        ),
    ]
