# Generated by Django 4.2.18 on 2025-01-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_saveduniversities_choiceno_saveduniversities_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveduniversities',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='saveduniversities',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
