# Generated by Django 4.2.18 on 2025-01-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_saveduniversities_lat_saveduniversities_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveduniversities',
            name='choiceNo',
        ),
        migrations.RemoveField(
            model_name='saveduniversities',
            name='major',
        ),
    ]
