# Generated by Django 4.2.18 on 2025-01-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma',
            name='CoLMax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='CoLMin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='CoLPrio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='ISRMax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='ISRMin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='ISRPrio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='accMax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='accMin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='accPrio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='groceryMax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='groceryMin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='groceryPrio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='healthcareBudgetMax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='healthcareBudgetMin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='healthcareBudgetPrio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='major',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='rankMax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='rankMin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='rankPrio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='recreationMax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='recreationMin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='recreationPrio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='rentMax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='rentMin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='rentPrio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='safetyMax',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='safetyMin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='safetyPrio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='transportMax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='transportMin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='transportPrio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='tuitionBudgetMax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='tuitionBudgetMin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma',
            name='tuitionBudgetPrio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
