# Generated by Django 4.2.18 on 2025-01-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_forma_colmax_alter_forma_colmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveduniversities',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='saveduniversities',
            name='lng',
            field=models.FloatField(),
        ),
    ]
